# This manifest creates a PersistentVolume (PV) that uses an existing EBS volume.
# Make sure to replace `vol-01ae7388ae0bb985e` with the actual volume ID of your EBS volume.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi # should be less than or equal to your disk size
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-01ae7388ae0bb985e   # create EBS disk in AZ's under us-east-1c
---
# This manifest creates a PersistentVolumeClaim (PVC) that binds to the above PV.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static # This is  the PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi